use std::fs::File;
use std::io::prelude::*;

fn main() {
    let input_text: Vec<&str> = "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"
        .split("\n")
        .collect();
    println!("{}", input_text[0]);
}

fn anti_nodes(text: Vec<&str>) {
    for line in text {
        println!("{line}");
        println!("{}", line.chars().nth(0));
    }
}
